server:
  port: 81

spring:
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
      static-path-pattern: /**
  resources:
      static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  application:
    name: mll-consumer

eureka:
  client:
    register-with-eureka: true
    service-url: 
      defaultZone: http://eureka6001.com:6001/eureka/
  instance:
    instance-id: mll-consumer-81
    prefer-ip-address: true     #访问路径可以显示IP地址
  redis:
    database: 0
    #host: 127.0.0.1
    host: 182.92.194.216
    password: 123456
    port: 6379
    timeout: 60s
    jedis:
      pool:
        max-idle: 50        # 最大空闲连接数
        min-idle: 10        # 最小空闲连接数
        max-wait:  -1s        # 等待可用连接的最大时间，负数为不限制
        max-active: -1        # 最大活跃连接数，负数为不限制
info:
  app.name: mll-microservice
  company.name: www.mll.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


#fegin的超时时间
feign:
  httpclient:
    connection-timeout: 30000
    enabled: true
  hystrix:
    enabled: false

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000


#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eureka:
    enabled: true

